#!/usr/bin/env node
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import readline from 'node:readline/promises';
import { args, appendJsonl, assertDependency, config, countJsonl, csvRecords, ensureDirs, exists, icon, jsonl, p, phase2Base, phases, readJson, root, runId, setState, shell, state, writeJson } from './lib.js';
import { checkProvider, generate } from './providers.js';
import { runPhase3, runPhase4, runPhase5, runPhase6 } from './research.js';
const a=args(); const command=a._[0]||'help'; const sub=a._[1];
const reviewSource='exports/atlassian_reviews.csv', appSource='exports/atlassian_apps.csv';
const out=(s='')=>console.log(s);
async function artifactStats(file) { const records=await jsonl(file), successIds=new Set(records.filter(x=>x.status==='success').map(x=>x.review_id)); return {success:successIds.size,failed:new Set(records.filter(x=>x.status==='failed'&&!successIds.has(x.review_id)).map(x=>x.review_id)).size}; }
function requireLimit(v) { if(v===undefined) return undefined; const n=Number(v); if(!Number.isInteger(n)||n<1) throw new Error('--limit must be a positive integer'); return n; }
function stamp(stage, review, settings, payload, status='success') { return {review_id:String(review.id),app_id:review.app_external_id||review.app_id||null,stage,status,provider:settings.provider,model:settings.model,analysis_version:'2026-09-12.2',prompt_version:'phase2-v2',schema_version:'1.0',started_at:new Date().toISOString(),completed_at:new Date().toISOString(),...payload}; }
function primaryPrompt(r) { return `Extract every problem, limitation, complaint, unmet need, or requested improvement explicitly stated in this marketplace review. Even a mostly positive review is actionable when it says something is still an issue, missing, difficult, limited, or should improve. Return JSON: {is_actionable:boolean,review_summary:string,customer_context:string|null,findings:[{finding_type:string,problem_statement:string,requested_solution:string|null,workflow:string|null,customer_segment:string|null,severity:number|null,business_impact:string|null,workaround:string|null,switching_intent:string|null,churn_intent:string|null,price_sensitivity:string|null,willingness_to_pay_signal:string|null,competitor_mentioned:string|null,integration_requested:string|null,confidence:number,evidence:string}]}. For pure praise or reviews without a concrete problem, return is_actionable=false and findings=[]. Do not create findings for praise. Unknown fields must be null. Each evidence value must be a short exact substring of the review. Review: ${JSON.stringify({stars:r.stars,content:r.content,title:r.title})}`; }
function verifyPrompt(r, primary) { return `Validate this extraction strictly against the review. Correct or remove anything not explicitly supported. Every factual field such as business impact, workaround, intent, pricing, competitor, integration, workflow, or customer segment must be null unless directly stated. Return JSON with decision (accept, correct, or unresolved) and result using the exact same extraction object shape. Review=${JSON.stringify(r.content)} Extraction=${JSON.stringify(primary.result)}`; }
function normalize(result, review) { if(!result || typeof result!=='object') throw new Error('model result is not an object'); const source=`${review?.title||''}\n${review?.content||''}`; let findings=Array.isArray(result.findings)?result.findings:[]; findings=findings.filter(f=>f&&typeof f.problem_statement==='string'&&f.problem_statement.trim()&&typeof f.evidence==='string'&&f.evidence.trim()&&source.includes(f.evidence.trim())); const grounded=['requested_solution','workflow','customer_segment','business_impact','workaround','switching_intent','churn_intent','price_sensitivity','willingness_to_pay_signal','competitor_mentioned','integration_requested']; for(const f of findings) { const confidence=Number(f.confidence); f.confidence=Number.isFinite(confidence)?Math.min(1,Math.max(0,confidence)):null; for(const key of grounded) if(typeof f[key]==='string'&&f[key].trim()&&!source.toLowerCase().includes(f[key].trim().toLowerCase())) f[key]=null; } const customerContext=typeof result.customer_context==='string'&&source.toLowerCase().includes(result.customer_context.trim().toLowerCase())?result.customer_context:null; return {...result,customer_context:customerContext,is_actionable:findings.length>0,findings}; }
async function importPhase1() { await ensureDirs(); if(!exists(reviewSource)||!exists(appSource)) throw new Error('Missing preserved CSV export(s) in exports/. No collection is performed.'); const targets=[['apps',appSource],['reviews',reviewSource]]; for(const [kind,source] of targets) { const dest=`data/phase1/${kind}.jsonl`; if(exists(dest)) {out(`${dest} already exists; leaving it unchanged.`);continue;} let n=0; out(`Importing ${source} → ${dest} (source remains untouched)…`); await csvRecords(source,async r=>{await appendJsonl(dest,r);n++; if(n%10000===0) out(`  ${n.toLocaleString()} records`);}); out(`  Imported ${n.toLocaleString()} ${kind}.`); }
 const reviews=await countJsonl('data/phase1/reviews.jsonl'), apps=await countJsonl('data/phase1/apps.jsonl'); await setState('phase1','complete',{apps,reviews,source:'preserved CSV exports'}); out(`Phase 1 imported safely: ${apps.toLocaleString()} apps, ${reviews.toLocaleString()} reviews.`); }
async function status() { const s=await state(), apps=await countJsonl('data/phase1/apps.jsonl'), reviews=await countJsonl('data/phase1/reviews.jsonl'); out('APP OPPORTUNITY MINER\n=====================\n\nProject:\nAtlassian Opportunity Research\n'); for(const [key,name] of phases) { let st=s.phases[key]?.status||'pending'; if(key==='phase1'&&reviews) st='complete'; out(`Phase ${key.slice(5)} — ${name}\n${'-'.repeat(32)}\nStatus: ${icon(st)} ${st.toUpperCase()}`); if(key==='phase1') out(`Apps: ${apps.toLocaleString()}\nReviews: ${reviews.toLocaleString()}`); if(key==='phase2') {for(const [label,file] of [['Primary','primary'],['Verification','verification'],['Finalization','final'],['Adjudication','adjudication']]) {const stats=await artifactStats(`data/phase2/${file}${file==='final'?'/reviews':''}.jsonl`);out(`${label}: ${stats.success.toLocaleString()} success${stats.failed?`, ${stats.failed} failed`:''}`);}} if(key!=='phase6')out(''); } if(exists('data/runs')) {const runs=await fsp.readdir(p('data/runs'),{withFileTypes:true});if(runs.some(x=>x.isDirectory()))out('\nIsolated test runs\n------------------');for(const entry of runs.filter(x=>x.isDirectory()).sort((x,y)=>x.name.localeCompare(y.name))){const base=`data/runs/${entry.name}/phase2`,primary=await artifactStats(`${base}/primary.jsonl`),verify=await artifactStats(`${base}/verification.jsonl`),adjudicate=await artifactStats(`${base}/adjudication.jsonl`),final=await artifactStats(`${base}/final/reviews.jsonl`),later=[];for(let phase=3;phase<=6;phase++){const m=await readJson(`data/runs/${entry.name}/phase${phase}/manifest.json`,null);later.push(`P${phase} ${m?.status==='complete'?'✅':'⏳'}`);}out(`${entry.name}: primary ${primary.success}${primary.failed?` (${primary.failed} failed)`:''}, verify ${verify.success}${verify.failed?` (${verify.failed} failed)`:''}, adjudicate ${adjudicate.success}${adjudicate.failed?` (${adjudicate.failed} failed)`:''}, final ${final.success}; ${later.join(', ')}`);}} if(!reviews) out('\nNext: npm run import:phase1'); else if(s.phases.phase2?.status!=='complete') {const c=await config(),checks=await Promise.all([checkProvider(c.models.primary),checkProvider(c.models.verifier),checkProvider(c.models.adjudicator),checkProvider(c.models.embedding)]);out(`\nNext safe command: ${checks.every(x=>x.ok)?'npm run test-pipeline -- --limit 10':'npm run models:install  (configured models are missing)'}`);} }
async function modelStatus(install=false) { const c=await config();let allReady=true;out('LOCAL MODEL STATUS\n=================='); for(const [role,m] of Object.entries(c.models)) { let ok=false, note=''; if(m.provider==='ollama') {try {const r=await fetch(`${m.baseUrl}/api/tags`); const data=await r.json(); ok=data.models?.some(x=>x.name===m.model||x.name.startsWith(`${m.model}:`));}catch{note='Ollama unavailable';} if(install&&!ok) {out(`Pulling ${m.model} for ${role} through the Ollama API…`); try {const r=await fetch(`${m.baseUrl}/api/pull`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:m.model,stream:false})});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,120)}`);ok=true;note='';}catch(e){note=e.message;}}} else {try {ok=(await fetch(`${m.baseUrl}/health`)).ok;}catch{note='endpoint unavailable';}} if(!ok)allReady=false;out(`\n${role}\n${m.provider}:${m.model}\n${ok?'✅ Installed / reachable':'❌ Missing / unreachable'}${note&&!ok?` (${note.trim().slice(0,100)})`:''}`); } return allReady; }
async function doctor() { out('SYSTEM CHECK\n============'); const rows=[]; rows.push(['Operating system',process.platform],['Node.js',process.version],['npm','available'],['Write permissions','checking']); try {await ensureDirs();await fsp.access(p('state'),fs.constants.W_OK);rows[3][1]='✅';}catch{rows[3][1]='❌';} for(const [k,v] of rows) out(`${k.padEnd(24)} ${v.startsWith('✅')||v.startsWith('❌')?v:'✅ '+v}`); out(`Phase 1 dataset          ${(exists('data/phase1/reviews.jsonl')||exists(reviewSource))?'✅ available':'❌ missing'}`); for(const file of ['data/phase1/reviews.jsonl','data/phase2/primary.jsonl','data/phase2/verification.jsonl','data/phase2/final/reviews.jsonl']) {try {await jsonl(file); if(exists(file))out(`JSONL ${file} ✅`);}catch(e){out(`JSONL ${file} ❌ ${e.message}`);}} const modelsReady=await modelStatus(false); out(`\nResult: ${modelsReady?'✅ SYSTEM READY. Next: npm run status':'⚠ SYSTEM PARTIALLY READY. Run: npm run models:install'}`); }
async function getReviews(limit, run) { const all=await jsonl('data/phase1/reviews.jsonl'); if(!all.length) throw new Error('Phase 1 JSONL is not imported. Run: npm run import:phase1'); return all.slice(0,limit||all.length); }
async function processStage(stage, options={}) { await assertDependency('phase2'); const c=await config(), run=runId(a), limit=requireLimit(a.limit), base=phase2Base(run); if(!limit && run==='production' && !a['confirm-full']) throw new Error('Full production run is protected. Review the workload, then use --confirm-full; for a safe test use --limit 10.'); const reviews=await getReviews(limit,run); await fsp.mkdir(p(base),{recursive:true}); const file=stage==='final'?`${base}/final/reviews.jsonl`:`${base}/${stage}.jsonl`; const done=new Set((await jsonl(file)).filter(x=>x.status==='success').map(x=>x.review_id)); const selected=reviews.filter(r=>!done.has(String(r.id))); if(run!=='production') await writeJson(`data/runs/${run}/manifest.json`,{run_id:run,dataset_id:'phase1-atlassian',review_limit:reviews.length,created_at:new Date().toISOString(),isolated:true});
 const primaryById=new Map((stage==='verification'?await jsonl(`${base}/primary.jsonl`):[]).filter(x=>x.status==='success').map(x=>[x.review_id,x]));
 const finalizedById=new Map((stage==='adjudication'?await jsonl(`${base}/finalization.jsonl`):[]).filter(x=>x.status==='success').map(x=>[x.review_id,x]));
 if(stage==='verification'&&!primaryById.size) throw new Error('Verification requires successful primary records for this run. Run phase2:primary first with the same --limit and --run-id.');
 if(stage==='adjudication'&&!finalizedById.size) throw new Error('Adjudication requires deterministic finalization records for this run. Run phase2:finalize first with the same --limit and --run-id.');
 const settingsForStage=stage==='primary'?c.models.primary:stage==='verification'?c.models.verifier:c.models.adjudicator;
 const candidates=stage==='primary'?selected:stage==='verification'?selected.filter(r=>primaryById.has(String(r.id))&&(a.force||primaryById.get(String(r.id)).result.is_actionable)):selected.filter(r=>finalizedById.has(String(r.id))&&(a.force||finalizedById.get(String(r.id)).needs_adjudication));
 out(`PHASE 2 — ${stage.toUpperCase()}\n${'='.repeat(32)}\nRun: ${run}\nModel: ${settingsForStage.model}\nDataset: ${reviews.length}\nCompleted before: ${done.size}\nCandidates remaining: ${candidates.length}`); if(a['dry-run']) return;
 if(candidates.length) { const ready=await checkProvider(settingsForStage); if(!ready.ok) throw new Error(`${stage} model unavailable: ${ready.reason}. Check npm run models:status or update .env.`); }
 const generation={numCtx:c.pipe.numCtx,numPredict:c.pipe.numPredict,keepAlive:c.pipe.keepAlive};
 for(const review of candidates) { const ordinal=reviews.indexOf(review)+1,settings=stage==='primary'?c.models.primary:stage==='verification'?c.models.verifier:c.models.adjudicator; try { let result; if(stage==='primary') { const x=await generate(settings,primaryPrompt(review),c.pipe.timeoutMs,c.pipe.maxRetries,generation); result=normalize(x.result,review); await appendJsonl(file,stamp(stage,review,settings,{latency_ms:x.latency_ms,attempts:x.attempts,provider_metadata:x.provider_metadata,result})); } else if(stage==='verification') {const prim=primaryById.get(String(review.id));const x=await generate(settings,verifyPrompt(review,prim),c.pipe.timeoutMs,c.pipe.maxRetries,generation); await appendJsonl(file,stamp(stage,review,settings,{latency_ms:x.latency_ms,attempts:x.attempts,provider_metadata:x.provider_metadata,decision:x.result.decision,result:normalize(x.result.result||prim.result,review)}));} else {const x=await generate(settings,primaryPrompt(review),c.pipe.timeoutMs,c.pipe.maxRetries,generation); await appendJsonl(file,stamp(stage,review,settings,{latency_ms:x.latency_ms,attempts:x.attempts,provider_metadata:x.provider_metadata,result:normalize(x.result,review)})); } out(`  ${ordinal}/${reviews.length} review ${review.id} ✅`); }catch(e) {await appendJsonl(file,stamp(stage,review,settings,{error:e.message,error_details:e.details||null},'failed')); out(`  ${ordinal}/${reviews.length} review ${review.id} ❌ ${e.message}`);} }
 if(run==='production') await setState('phase2','in_progress',{[stage]:{completed:await countJsonl(file)}}); }
async function finalize(preliminary=false) { await assertDependency('phase2'); const run=runId(a),base=phase2Base(run), limit=requireLimit(a.limit), reviews=await getReviews(limit), primary=await jsonl(`${base}/primary.jsonl`), verification=await jsonl(`${base}/verification.jsonl`), adjudication=await jsonl(`${base}/adjudication.jsonl`), file=preliminary?`${base}/finalization.jsonl`:`${base}/final/reviews.jsonl`; const done=new Set((await jsonl(file)).filter(x=>x.status==='success').map(x=>x.review_id)); let n=0; for(const r of reviews){if(done.has(String(r.id)))continue;const q=primary.find(x=>x.review_id===String(r.id)&&x.status==='success');if(!q)continue;const v=verification.find(x=>x.review_id===String(r.id)&&x.status==='success');const adj=adjudication.find(x=>x.review_id===String(r.id)&&x.status==='success');const candidate=normalize(v?.result||q.result,r);const low=(candidate.findings||[]).some(f=>(f.confidence??0)<0.55);if(!preliminary&&(low||a.force)&&!adj)continue;const result=normalize(adj?.result||candidate,r);await appendJsonl(file,{review_id:String(r.id),app_id:r.app_external_id,stage:preliminary?'finalization':'final',status:'success',analysis_version:'2026-09-12.2',final_source:adj?'adjudication':v?'verification':'primary',needs_adjudication:preliminary?low:false,result,completed_at:new Date().toISOString()});n++;} out(`${preliminary?'Prepared':'Finalized'} ${n} reviews deterministically.`); if(!preliminary&&run==='production'&&reviews.length===await countJsonl(file)) await setState('phase2','complete',{finalized:reviews.length}); }
async function phase2() { await processStage('primary'); await processStage('verification'); await finalize(true); await processStage('adjudication'); await finalize(false); }
async function failures() {const run=runId(a),base=phase2Base(run);out(`PIPELINE FAILURES\n=================\nRun: ${run}`); for(const st of ['primary','verification','adjudication']) {const records=await jsonl(`${base}/${st}.jsonl`),successIds=new Set(records.filter(x=>x.status==='success').map(x=>x.review_id)),xs=records.filter(x=>x.status==='failed'&&!successIds.has(x.review_id));out(`\nPhase 2 ${st}: ${xs.length}`); for(const x of xs.slice(-5))out(`Review ${x.review_id} | ${x.model} | ${x.error}`);}const critic=await jsonl(`${run==='production'?'data/phase5':`data/runs/${run}/phase5`}/critic-results.jsonl`),criticSuccess=new Set(critic.filter(x=>x.status==='success').map(x=>x.opportunity_id)),criticFailed=critic.filter(x=>x.status==='failed'&&!criticSuccess.has(x.opportunity_id));out(`\nPhase 5 Business Critic: ${criticFailed.length}`);for(const x of criticFailed.slice(-5))out(`Opportunity ${x.opportunity_id} | ${x.model} | ${x.error}`);}
async function dbBuild(rebuild=false) {await ensureDirs();const file=p('data/app-opportunity-miner.sqlite');if(rebuild&&fs.existsSync(file))fs.rmSync(file);const { DatabaseSync }=await import('node:sqlite');const db=new DatabaseSync(file);db.exec('CREATE TABLE IF NOT EXISTS phase1_reviews (id TEXT PRIMARY KEY, app_id TEXT, stars TEXT, content TEXT, raw_json TEXT); CREATE TABLE IF NOT EXISTS phase2_final (review_id TEXT PRIMARY KEY, app_id TEXT, result_json TEXT);');const insert=db.prepare('INSERT OR REPLACE INTO phase1_reviews VALUES (?,?,?,?,?)');db.exec('BEGIN');for(const r of await jsonl('data/phase1/reviews.jsonl')) insert.run(String(r.id),r.app_external_id||'',r.stars||'',r.content||'',JSON.stringify(r));const finalInsert=db.prepare('INSERT OR REPLACE INTO phase2_final VALUES (?,?,?)');for(const r of await jsonl('data/phase2/final/reviews.jsonl'))finalInsert.run(r.review_id,r.app_id||'',JSON.stringify(r));db.exec('COMMIT');out(`SQLite index rebuilt: ${file}`);db.close();}
async function wizard(){out('APP OPPORTUNITY MINER\n=====================');if(!process.stdin.isTTY){out('\nNon-interactive session: no model work started.\nUse: npm run status | npm run phase2 -- --limit 10 | npm run failures');return;}const rl=readline.createInterface({input:process.stdin,output:process.stdout});try{out('\n1) Show current project status\n2) Test complete Phase 2 pipeline (10 reviews)\n3) Inspect failures\n4) Check models');const choice=await rl.question('\nChoose [1-4]: ');if(choice==='1')await status();else if(choice==='3')await failures();else if(choice==='4')await modelStatus(false);else if(choice==='2'){const yes=await rl.question('Run isolated 10-review test using configured local models? [y/N] ');if(/^y(es)?$/i.test(yes)){a.limit='10';await phase2();}else out('Cancelled.');}else out('No action selected.');}finally{rl.close();}}
async function bootstrap(){await ensureDirs();if(!exists('.env'))await fsp.copyFile(p('.env.example'),p('.env'));out(`Bootstrap prepared directories and ${exists('.env')?'preserved/created .env':''}.`);await doctor();}
async function withRunLock(work) {await fsp.mkdir(p('state/locks'),{recursive:true});const id=runId(a).replace(/[^a-zA-Z0-9._-]/g,'_'),file=p(`state/locks/${id}.lock`);let handle;try{handle=await fsp.open(file,'wx');await handle.writeFile(JSON.stringify({pid:process.pid,run_id:id,started_at:new Date().toISOString()})+'\n');return await work();}catch(e){if(e.code==='EEXIST')throw new Error(`Run ${id} is already active. Wait for it to finish; inspect ${file}.`);throw e;}finally{if(handle){await handle.close();await fsp.unlink(file).catch(()=>{});}}}
async function main(){try {if(command==='status')await status();else if(command==='doctor')await doctor();else if(command==='models')await modelStatus(sub==='install');else if(command==='import'&&sub==='phase1')await importPhase1();else if(command==='phase1')await importPhase1();else if(command==='phase2')await withRunLock(async()=>{if(sub==='finalize')await finalize(true);else if(sub==='primary')await processStage('primary');else if(sub==='verify')await processStage('verification');else if(sub==='adjudicate')await processStage('adjudication');else await phase2();});else if(command==='test-pipeline'){if(!a.limit)a.limit='10';await withRunLock(async()=>{await phase2();const run=runId(a);await runPhase3({run});await runPhase4({run});await runPhase5({run,dryRun:Boolean(a['dry-run'])});if(!a['dry-run'])await runPhase6({run});});}else if(command==='phase3')await withRunLock(()=>runPhase3({run:runId(a)}));else if(command==='phase4')await withRunLock(()=>runPhase4({run:runId(a)}));else if(command==='phase5')await withRunLock(()=>runPhase5({run:runId(a),dryRun:Boolean(a['dry-run'])}));else if(command==='phase6')await withRunLock(()=>runPhase6({run:runId(a)}));else if(command==='failures')await failures();else if(command==='db') {if(sub==='status')out(exists('data/app-opportunity-miner.sqlite')?'✅ SQLite index exists':'⏳ SQLite index absent; run npm run db:build');else await dbBuild(sub==='rebuild');}else if(command==='wizard')await wizard();else if(command==='bootstrap')await bootstrap();else out('Usage: npm run status | doctor | test-pipeline -- --limit 10 | phase2 | phase3 | phase4 | phase5 | phase6');}catch(e){console.error(`\n${e.message}`);process.exitCode=1;}}
main();
