import crypto from 'node:crypto';
import fsp from 'node:fs/promises';
import { appendJsonl, config, countJsonl, exists, jsonl, p, phaseBase, readJson, setState, writeJson, writeJsonl } from './lib.js';
import { checkProvider, embedTexts, generate } from './providers.js';

const now=()=>new Date().toISOString();
const stableId=(prefix,text)=>`${prefix}-${crypto.createHash('sha256').update(text).digest('hex').slice(0,16)}`;
function normalized(vector){const norm=Math.sqrt(vector.reduce((s,x)=>s+x*x,0))||1;return Float64Array.from(vector,x=>x/norm);}
function cosine(a,b){let dot=0,na=0,nb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];na+=a[i]*a[i];nb+=b[i]*b[i];}return na&&nb?dot/Math.sqrt(na*nb):0;}
function avg(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;}
async function manifest(phase,run){return readJson(`${phaseBase(phase,run)}/manifest.json`,null);}
async function writeManifest(phase,run,data){await writeJson(`${phaseBase(phase,run)}/manifest.json`,{phase,status:'complete',run_id:run,completed_at:now(),...data});if(run==='production')await setState(`phase${phase}`,'complete',data);}
async function expectedReviews(run){if(run==='production')return countJsonl('data/phase1/reviews.jsonl');const m=await readJson(`data/runs/${run}/manifest.json`,null);return m?.review_limit||0;}
async function latestSuccess(file,key){const map=new Map();for(const x of await jsonl(file))if(x.status==='success')map.set(String(x[key]),x);return [...map.values()];}

export async function assertResearchDependency(phase,run){
  if(phase===3){const expected=await expectedReviews(run),actual=(await latestSuccess(`${phaseBase(2,run)}/final/reviews.jsonl`,'review_id')).length;if(!expected||actual<expected)throw new Error(`Cannot start Phase 3 for run ${run}. Phase 2 final dataset has ${actual}/${expected||'unknown'} reviews.\nRecommended: npm run phase2 -- --limit ${expected||10}${run.startsWith('test-')?'':` --run-id ${run}`}`);return;}
  const prior=await manifest(phase-1,run);if(prior?.status!=='complete')throw new Error(`Cannot start Phase ${phase} for run ${run}. Phase ${phase-1} is not complete.\nRecommended: npm run phase${phase-1} -- --run-id ${run}`);
}

export async function runPhase3({run,log=console.log}){
  await assertResearchDependency(3,run);const c=await config(),threshold=c.pipe.phase3?.similarityThreshold||0.72,batchSize=c.pipe.phase3?.embeddingBatchSize||64,model=c.models.embedding,base=phaseBase(3,run),finals=await latestSuccess(`${phaseBase(2,run)}/final/reviews.jsonl`,'review_id'),apps=await jsonl('data/phase1/apps.jsonl'),appNames=new Map(apps.map(x=>[String(x.external_id),x.name])),reviews=await jsonl('data/phase1/reviews.jsonl'),reviewById=new Map(reviews.map(x=>[String(x.id),x])),items=[];
  for(const record of finals)for(const [findingIndex,finding] of (record.result?.findings||[]).entries()){const review=reviewById.get(String(record.review_id))||{};const text=[finding.problem_statement,finding.requested_solution,finding.workflow].filter(Boolean).join(' ');items.push({finding_id:stableId('finding',`${record.review_id}:${findingIndex}:${text}`),review_id:String(record.review_id),app_id:record.app_id||review.app_external_id||null,app_name:appNames.get(String(record.app_id||review.app_external_id))||null,rating:Number(review.stars)||null,finding_index:findingIndex,finding,text});}
  items.sort((a,b)=>a.finding_id.localeCompare(b.finding_id));const embeddingFile=`${base}/embeddings/findings.jsonl`,existing=await jsonl(embeddingFile),vectorById=new Map();for(const record of existing)if(record.status==='success'&&record.embedding?.model===model.model&&Array.isArray(record.embedding.values))vectorById.set(record.finding_id,normalized(record.embedding.values));const pending=items.filter(x=>!vectorById.has(x.finding_id));if(pending.length){const ready=await checkProvider(model);if(!ready.ok)throw new Error(`Embedding model unavailable: ${ready.reason}. Run npm run models:install.`);}for(let i=0;i<pending.length;i+=batchSize){const batch=pending.slice(i,i+batchSize),x=await embedTexts(model,batch.map(y=>y.text),c.pipe.timeoutMs,c.pipe.keepAlive);for(let j=0;j<batch.length;j++){const vector=normalized(x.embeddings[j]);vectorById.set(batch[j].finding_id,vector);await appendJsonl(embeddingFile,{...batch[j],stage:'embedding',status:'success',provider:model.provider,model:model.model,completed_at:now(),embedding:{provider:model.provider,model:model.model,dimensions:vector.length,values:Array.from(vector)}});}log(`Embedded ${Math.min(i+batch.length,pending.length)}/${pending.length} remaining findings`);}const vectors=items.map(x=>vectorById.get(x.finding_id)),dims=vectors[0]?.length||0,clusters=[];
  for(let itemIndex=0;itemIndex<items.length;itemIndex++){const item=items[itemIndex],vec=vectors[itemIndex];let best=-1,score=-1;for(let i=0;i<clusters.length;i++){const s=cosine(vec,clusters[i].centroid);if(s>score){score=s;best=i;}}if(best<0||score<threshold)clusters.push({members:[item],vectors:[vec],centroid:vec});else{const cl=clusters[best],n=cl.members.length;for(let i=0;i<dims;i++)cl.centroid[i]=(cl.centroid[i]*n+vec[i])/(n+1);cl.members.push(item);cl.vectors.push(vec);}}
  const clusterRecords=clusters.map(cl=>{const members=cl.members,statements=members.map(x=>x.finding.problem_statement),name=statements.sort((a,b)=>a.length-b.length||a.localeCompare(b))[0]||'Unlabelled problem',apps=new Set(members.map(x=>x.app_id).filter(Boolean)),reviews=new Set(members.map(x=>x.review_id));return {cluster_id:stableId('cluster',members.map(x=>x.finding_id).sort().join('|')),cluster_name:name,is_recurring:members.length>=2,finding_count:members.length,unique_reviews:reviews.size,unique_apps:apps.size,average_severity:avg(members.map(x=>Number(x.finding.severity)).filter(Number.isFinite)),finding_ids:members.map(x=>x.finding_id),representative_findings:members.slice(0,5).map(x=>({finding_id:x.finding_id,review_id:x.review_id,app_id:x.app_id,app_name:x.app_name,rating:x.rating,problem_statement:x.finding.problem_statement,evidence:x.finding.evidence,severity:x.finding.severity,business_impact:x.finding.business_impact,requested_solution:x.finding.requested_solution,willingness_to_pay_signal:x.finding.willingness_to_pay_signal,churn_intent:x.finding.churn_intent,competitor_mentioned:x.finding.competitor_mentioned})),embedding_provider:model.provider,embedding_model:model.model,similarity_threshold:threshold};});
  await writeJsonl(`${base}/clusters.jsonl`,clusterRecords);await writeManifest(3,run,{input_reviews:finals.length,input_findings:items.length,clusters:clusterRecords.length,embedding_provider:model.provider,embedding_model:model.model,config:{dimensions:dims,similarity_threshold:threshold,batch_size:batchSize}});log(`PHASE 3 COMPLETE — ${items.length} findings → ${clusterRecords.length} clusters (${pending.length} new embeddings)\nArtifacts: ${base}/clusters.jsonl`);return clusterRecords;
}

export async function runPhase4({run,log=console.log}){
  await assertResearchDependency(4,run);const c=await config(),weights=c.pipe.phase4?.weights||{},clusters=await jsonl(`${phaseBase(3,run)}/clusters.jsonl`),opportunities=clusters.map(cl=>{const reps=cl.representative_findings||[],findings=cl.finding_count||0,frequency=Math.min(1,Math.log1p(findings)/Math.log1p(50)),appBreadth=Math.min(1,(cl.unique_apps||0)/10),severity=Math.min(1,(cl.average_severity||2)/5),businessImpact=reps.length?reps.filter(x=>x.business_impact).length/reps.length:0,demand=reps.length?reps.filter(x=>x.requested_solution||x.willingness_to_pay_signal||x.churn_intent).length/reps.length:0,components={frequency,app_breadth:appBreadth,severity,business_impact:businessImpact,demand},score=100*((weights.frequency||.3)*frequency+(weights.appBreadth||.2)*appBreadth+(weights.severity||.2)*severity+(weights.businessImpact||.15)*businessImpact+(weights.demand||.15)*demand);return {opportunity_id:stableId('opportunity',cl.cluster_id),cluster_id:cl.cluster_id,opportunity_name:`Improve: ${cl.cluster_name}`,problem_being_solved:cl.cluster_name,evidence_strength:cl.is_recurring?'recurring':'singleton_test_signal',evidence_metrics:{finding_count:findings,unique_reviews:cl.unique_reviews,unique_apps:cl.unique_apps,average_severity:cl.average_severity},commercial_signals:{business_impact_mentions:reps.filter(x=>x.business_impact).length,demand_mentions:reps.filter(x=>x.requested_solution).length,willingness_to_pay_mentions:reps.filter(x=>x.willingness_to_pay_signal).length,churn_mentions:reps.filter(x=>x.churn_intent).length,competitor_mentions:reps.filter(x=>x.competitor_mentioned).length},score:{total:Number(score.toFixed(2)),components,weights,method:'weighted-evidence-v1'},supporting_evidence:reps,unknowns:['competitor_strength','competitor_pricing','market_saturation','platform_api_risk','technical_feasibility'],interpretation:cl.is_recurring?'Candidate derived from a recurring problem cluster; unknown commercial factors require criticism.':'Singleton signal retained only so isolated tests can exercise later phases; it is not recurring evidence.',created_at:now()};}).sort((a,b)=>b.score.total-a.score.total||a.opportunity_id.localeCompare(b.opportunity_id));await writeJsonl(`${phaseBase(4,run)}/opportunities.jsonl`,opportunities);await writeManifest(4,run,{input_clusters:clusters.length,opportunities:opportunities.length,scoring_method:'weighted-evidence-v1',weights});log(`PHASE 4 COMPLETE — ${opportunities.length} inspectable opportunities scored\nArtifacts: ${phaseBase(4,run)}/opportunities.jsonl`);return opportunities;
}

function criticPrompt(o){return `Act as a skeptical business critic. Do not invent facts. Clearly label inference and unknowns. Attack this opportunity: why unsolved, willingness to pay, Atlassian native risk, incumbents, feature-vs-product risk, support burden, API sufficiency, solo developer feasibility, market size, differentiation. Return JSON {verdict:"SURVIVES"|"WEAK"|"REJECT"|"NEEDS_MORE_EVIDENCE",summary:string,major_risks:[string],survival_reasons:[string],missing_evidence:[string],platform_native_risk:"low"|"medium"|"high"|"unknown",solo_developer_feasibility:"low"|"medium"|"high"|"unknown",confidence:number}. Evidence candidate: ${JSON.stringify(o)}`;}
export function normalizeCritic(x){const verdicts=new Set(['SURVIVES','WEAK','REJECT','NEEDS_MORE_EVIDENCE']),levels=new Set(['low','medium','high','unknown']);return {verdict:verdicts.has(x?.verdict)?x.verdict:'NEEDS_MORE_EVIDENCE',summary:String(x?.summary||'Insufficient critic output.'),major_risks:Array.isArray(x?.major_risks)?x.major_risks.map(String):[],survival_reasons:Array.isArray(x?.survival_reasons)?x.survival_reasons.map(String):[],missing_evidence:Array.isArray(x?.missing_evidence)?x.missing_evidence.map(String):[],platform_native_risk:levels.has(x?.platform_native_risk)?x.platform_native_risk:'unknown',solo_developer_feasibility:levels.has(x?.solo_developer_feasibility)?x.solo_developer_feasibility:'unknown',confidence:Math.min(1,Math.max(0,Number(x?.confidence)||0))};}
export async function runPhase5({run,log=console.log,dryRun=false}){
  await assertResearchDependency(5,run);const c=await config(),base=phaseBase(5,run),file=`${base}/critic-results.jsonl`,opportunities=await jsonl(`${phaseBase(4,run)}/opportunities.jsonl`),done=new Set((await latestSuccess(file,'opportunity_id')).map(x=>x.opportunity_id)),pending=opportunities.filter(x=>!done.has(x.opportunity_id)),model=c.models.adjudicator;log(`PHASE 5 — BUSINESS CRITIC\nModel: ${model.model}\nCandidates: ${opportunities.length}\nCompleted: ${done.size}\nRemaining: ${pending.length}`);if(dryRun)return [];
  if(pending.length){const ready=await checkProvider(model);if(!ready.ok)throw new Error(`Business Critic model unavailable: ${ready.reason}`);}let failed=0;for(const [i,o] of pending.entries())try{const x=await generate(model,criticPrompt(o),c.pipe.timeoutMs,c.pipe.maxRetries,{numCtx:c.pipe.numCtx,numPredict:c.pipe.numPredict,keepAlive:c.pipe.keepAlive});await appendJsonl(file,{opportunity_id:o.opportunity_id,cluster_id:o.cluster_id,stage:'business_critic',status:'success',provider:model.provider,model:model.model,analysis_version:c.pipe.analysisVersion,prompt_version:'business-critic-v1',latency_ms:x.latency_ms,attempts:x.attempts,completed_at:now(),result:normalizeCritic(x.result)});log(`  ${i+1}/${pending.length} ${o.opportunity_id} ✅`);}catch(e){failed++;await appendJsonl(file,{opportunity_id:o.opportunity_id,cluster_id:o.cluster_id,stage:'business_critic',status:'failed',provider:model.provider,model:model.model,completed_at:now(),error:e.message,error_details:e.details||null});log(`  ${i+1}/${pending.length} ${o.opportunity_id} ❌ ${e.message}`);}const success=(await latestSuccess(file,'opportunity_id')).length;if(failed)throw new Error(`Phase 5 stopped with ${failed} unresolved failure(s). Inspect the Phase 5 JSONL for run ${run}.`);await writeManifest(5,run,{input_opportunities:opportunities.length,critic_results:success,model:model.model,prompt_version:'business-critic-v1'});log(`PHASE 5 COMPLETE — ${success} opportunities criticized`);return latestSuccess(file,'opportunity_id');
}

export async function runPhase6({run,log=console.log}){
  await assertResearchDependency(6,run);const opportunities=await jsonl(`${phaseBase(4,run)}/opportunities.jsonl`),critics=await latestSuccess(`${phaseBase(5,run)}/critic-results.jsonl`,'opportunity_id'),criticById=new Map(critics.map(x=>[x.opportunity_id,x.result])),adjust={SURVIVES:10,WEAK:-15,REJECT:-100,NEEDS_MORE_EVIDENCE:-5},assessed=opportunities.map(o=>{const critic=criticById.get(o.opportunity_id),finalScore=Math.max(0,Math.min(100,o.score.total+(adjust[critic?.verdict]??-5)));return {...o,business_critic:critic||null,final_score:Number(finalScore.toFixed(2))};}),ranked=assessed.filter(x=>x.business_critic?.verdict!=='REJECT').sort((a,b)=>b.final_score-a.final_score||a.opportunity_id.localeCompare(b.opportunity_id)).map((x,i)=>({...x,rank:i+1})),rejected=assessed.filter(x=>x.business_critic?.verdict==='REJECT'),report={report_title:'App Opportunity Miner — Final Opportunity Report',run_id:run,generated_at:now(),methodology:{evidence:'Marketplace reviews and Phase 2 grounded findings',calculated_metrics:'Phase 3 semantic clusters and Phase 4 weighted-evidence-v1 score',llm_interpretation:'Phase 5 Business Critic, explicitly stored with model provenance',recommendation:'Ranked by evidence score adjusted by critic verdict'},ranked_opportunities:ranked,rejected_opportunities:rejected};const base=phaseBase(6,run);await writeJson(`${base}/final-report-data.json`,report);const md=['# Final Opportunity Report','',`Run: ${run}`,`Generated: ${report.generated_at}`,'',ranked.length?'## Ranked opportunities':'No opportunities survived with the available evidence.',''];for(const x of ranked)md.push(`## ${x.rank}. ${x.opportunity_name}`,'',`Final score: ${x.final_score}/100  `,`Business Critic: ${x.business_critic.verdict}  `,`Evidence: ${x.evidence_metrics.finding_count} findings across ${x.evidence_metrics.unique_reviews} reviews and ${x.evidence_metrics.unique_apps} apps.`,'',x.problem_being_solved,'','Risks:',...(x.business_critic.major_risks||[]).map(r=>`- ${r}`),'','Why it survived:',...(x.business_critic.survival_reasons||[]).map(r=>`- ${r}`),'');if(rejected.length){md.push('## Rejected candidates','');for(const x of rejected)md.push(`### ${x.opportunity_name}`,'',`Evidence score: ${x.score.total}/100  `,`Verdict: ${x.business_critic.verdict}`,'',x.business_critic.summary,'','Risks:',...(x.business_critic.major_risks||[]).map(r=>`- ${r}`),'');}await fsp.mkdir(p(base),{recursive:true});await fsp.writeFile(p(`${base}/FINAL_REPORT.md`),md.join('\n')+'\n');await writeManifest(6,run,{ranked_opportunities:ranked.length,rejected_opportunities:rejected.length,report_data:'final-report-data.json',report_markdown:'FINAL_REPORT.md'});log(`PHASE 6 COMPLETE — ${ranked.length} ranked, ${rejected.length} rejected\nReport: ${base}/FINAL_REPORT.md`);return report;
}
